### 설문조사 생성 API
POST http://localhost:10001/c/create-survey
Content-Type: application/json

{
  "name": "설문조사 이름",
  "description": "설문조사 설명",
  "items": [
    {
      "type": "SINGLE_CHOICE",
      "name": "단일 선택 리스트 설문조사 이름",
      "description": "단일 선택 리스트 설문조사 설명",
      "optionNames": [
        "option1"
      ],
      "required": true
    },
    {
      "type": "MULTIPLE_CHOICE",
      "name": "다중 선택 리스트 설문조사 이름",
      "description": "다중 선택 리스트 설문조사 설명",
      "optionNames": [
        "option1",
        "option2",
        "option3"
      ],
      "required": true
    },
    {
      "type": "SHORT_TEXT",
      "name": "단답형 설문조사 이름",
      "description": "단답형 설문조사 설명",
      "required": true
    },
    {
      "type": "LONG_TEXT",
      "name": "장문형 설문조사 이름",
      "description": "장문형 설문조사 설명",
      "required": true
    }
  ]
}
